## Numerical Python
 - Linear Algebra
 - Has bindings to C
 - High performing Library

In [1]:
import numpy as np

In [2]:
lst_data = list(range(1, 11))

In [3]:
print(lst_data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
print(type(lst_data))

<class 'list'>


In [7]:
e = np.array(lst_data)

In [12]:
type(np.array(lst_data))

numpy.ndarray

In [9]:
print(e.shape)
print(e.ndim)

(10,)
1


In [10]:
e = np.array([lst_data])

In [15]:
print(e.shape)
print(e.ndim)
print(type(e))
print(e)

(1, 10)
2
<class 'numpy.ndarray'>
[[ 1  2  3  4  5  6  7  8  9 10]]


In [16]:
mat1 = [[1, 2, 3, 4],[5, 6, 7, 8]]

In [17]:
mat1 = np.array(mat1)

In [19]:
mat1.shape

(2, 4)

In [20]:
mat1.ndim

2

In [73]:
mat1 = [[[1, 2, 3, 4],[5, 6, 7, 8]],[[1, 2, 3, 4],[5, 6, 7, 8]]]

In [75]:
mat1 = np.array(mat1)

In [76]:
mat1

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [31]:
mat1.ndim

3

In [32]:
mat1

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [24]:
mat1.shape

(2, 2, 4)

In [60]:
my_list = [1, 2, 3, 4, 5, 6]

In [61]:
arr1 = np.array(my_list, dtype = int)

In [62]:
arr1

array([1, 2, 3, 4, 5, 6])

In [63]:
arr1.shape

(6,)

In [64]:
arr2 = arr1.reshape(3, 2)

In [65]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
lis1 = list(range(1,6))
lis2 = list(range(10,15))
lis3 = list(range(20, 25))

In [67]:
arr4 = np.array([lis1, lis2, lis3])

In [68]:
arr4

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [69]:
arr4.shape

(3, 5)

In [71]:
arr4.reshape(1, 15)

array([[ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24]])

In [72]:
arr4.reshape(-1)

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24])

In [ ]:
new_array = np.random.randint(10,20,100)

In [ ]:
new_arr

In [ ]:
new_array = np.random.randn(10,25)

In [ ]:
new_arr

In [ ]:
np.mean(new_array)

In [ ]:
x = np.array([[1,2,3],[4,5,6]])

In [ ]:
y = np.array([[8,9,7],[6,3,6]])

In [ ]:
x

In [ ]:
y

In [ ]:
x+y

In [ ]:
x-y

In [ ]:
x*y

In [ ]:
np.add(x,y)

In [ ]:
np.multiply(x,y)

In [ ]:
arr = np.range(10)

In [ ]:
arr

In [ ]:
arr = np.range(10,21,2)

In [ ]:
arr

In [ ]:
arr = arr.reshape(2, 3)

In [ ]:
arr

In [ ]:
arr.T

In [ ]:
np.max(arr)

In [ ]:
np.min(arr)

In [ ]:
np.zeros((3,3))

In [ ]:
arr

In [ ]:
arr[1]

# Loading Data and Import Pandas

In [1]:
# Pandas Intro

In [2]:
#import pandas

In [3]:
#!conda install pandas

In [4]:
#import pandas as pd

In [5]:
#data_iris = pd.read_csv("../datasets/Iris_data_sample.csv")

In [6]:
#data_iris

In [7]:
#data_iris = pd.read_excel("../datasets/Iris_data_sample.xlsx")

In [ ]:
#data_iris.head()